<a href="https://colab.research.google.com/github/DarraghQV/Algorithms/blob/master/Genetic_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
def sphere(x):

  total = 0
  for i in x:
    total += i*i
    return total

In [5]:
x = [1,2,3]
sphere(x)

1

In [6]:
y = [2,3,4]
sphere(y)

4

In [9]:
z = [-1,-2,-3]
sphere(z)

1

In [21]:
class problem:
  def __init__(self):
    self.number_of_genes = 8
    self.min_value = -10
    self.max_value = 10
    self.cost_function = sphere
    pass

In [135]:
import numpy as np
from copy import deepcopy

class individual:
  def __init__(self, prob):
    self.chromosome = np.random.uniform(prob.min_value, prob.max_value, prob.number_of_genes)
    self.cost = prob.cost_function(self.chromosome)

  def mutate(self, rate_of_gene_mutation, range_of_gene_mutation):
    for index in range(len(self.chromosome)):
      if np.random.uniform() < rate_of_gene_mutation:
        self.chromosome[index] += np.random.randn() * range_of_gene_mutation

  def crossover(self, parent2, explore_crossover):
    alpha = np.random.uniform(-explore_crossover, 1+explore_crossover)
    child1.chromosome = deepcopy(self)
    child2.chromosome = deepcopy(parent2)
    child1.chromosome = alpha * self.chromosome + (1-alpha) * parent2.chromosome
    child2.chromosome = alpha * parent2.chromosome + (1-alpha) * self.chromosome
    return child1, child2


In [149]:
class parameters:
  def __init__(self):
    self.population_size = 1000

In [154]:
def run_genetic(prob):
  # Read variables

  # Create our population
  population = []
  for i in range(1000):
    population.append(individual(p))

  # Start loop

    # Create children

    # Sort population

    # Cull population

    # Check solution

In [136]:
p = problem()

In [137]:
p.number_of_genes

8

In [138]:
i1 = individual(p)

In [139]:
i1.chromosome

array([ 1.93002116,  7.94696564,  1.10153085, -2.2974523 ,  9.9317691 ,
       -0.62888699, -1.70444038, -7.67244376])

In [140]:
i1.mutate(0.5, 2)

In [141]:
i1.chromosome

array([ 1.93002116,  7.94696564,  1.10153085, -2.2974523 ,  9.9317691 ,
       -0.62888699,  0.01981821, -6.44123519])

In [142]:
i2 = individual(p)

In [143]:
i2.chromosome

array([ 7.89424131,  6.29707174,  4.13039736,  4.63877531,  1.32741142,
       -2.48915932, -7.0841476 ,  8.80049205])

In [144]:
i1.chromosome

array([ 1.93002116,  7.94696564,  1.10153085, -2.2974523 ,  9.9317691 ,
       -0.62888699,  0.01981821, -6.44123519])

NameError: name 'c1' is not defined

In [52]:
population = []
for i in range(1000):
  population.append(individual(p))


In [53]:
population

In [54]:
i1.mutate(0.5, 2)

TypeError: only integer scalar arrays can be converted to a scalar index